repos:
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
        args:
          - --number
          - --wrap=keep
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
        args:
          - --allow-multiple-documents
      - id: forbid-submodules
      - id: mixed-line-ending
        args:
          - --fix=auto
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
